#!/bin/sh
#PBS -N evaluate_layers
#PBS -m bea
#PBS -M jklynch@email.arizona.edu
#PBS -W group_list=bhurwitz
#PBS -q standard
#PBS -l select=1:ncpus=28:mem=168gb
#PBS -l walltime=04:00:00

source activate ktf

export OMP_NUM_THREADS=28

`pwd`
cd ~/project/viral-learning/vl/train/nn

python train_nn_meta_genome.py \
    --input-fp /extra/jklynch/viral-learning/perm_training_testing.h5 \
    --training-sample-count 100000 \
    --dev-sample-count 2000 \
    --half-batch-count 50 \
    --epoch-count 20
